apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  labels:
    app: {{ .Values.application.label }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.application.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.label }}
    spec:
      containers:
      - name: application-backend
        image: {{ .Values.application.image.repository }}:v{{ default .Chart.AppVersion  .Values.application.image.version}}
        ports:
        - containerPort: {{ .Values.application.port }}
        livenessProbe:
          httpGet:
            port: {{ .Values.application.port }}
        readinessProbe:
          httpGet:
            port: {{ .Values.application.port }}
