apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.application.label }}
  ports:
  - name: hello-world-default-port
    port: {{ .Values.ingress.port }}
    targetPort: {{ .Values.application.port }}
