apiVersion: k3d.io/v1alpha2
kind: Simple
name: dev
servers: 1
agents: 0
image: rancher/k3s:v1.20.4-k3s1
ports:
  - port: 8081:80
    nodeFilters:
      - server[0]

options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
  k3s:
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
